# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nile_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_favorite', to='nile_backend.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_owner', to='nile_backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolve_recipient', 'Resolved recipient'), ('delivered', 'delivered'), ('returned', 'returned')], default='open', max_length=31)),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pac_deliverer', to='nile_backend.User')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pac_purchaser', to='nile_backend.User')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pac_recipient', to='nile_backend.User')),
            ],
        ),
    ]
