# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nile_backend', '0002_favorite_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 2, 13, 34, 25, 863583, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 2, 13, 34, 36, 277237, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 2, 13, 34, 41, 545242, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 2, 13, 34, 45, 757952, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
