# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nile_backend', '0004_auto_20160702_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
