# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nile_backend', '0006_auto_20160702_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('deliverer', 'Deliverer')], default='client', max_length=31),
        ),
    ]
