# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nile_backend', '0007_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
